substitutions:
  name: "esp01-jk48v100"
  friendly_name: "ESP-01 - JK48V100 Battery"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev

esp8266:
  board: esp01_1m

logger:
  hardware_uart: UART1 
  level: VERBOSE

ota:
- platform: esphome

wifi:
  ap: {}

web_server:
  version: 3

external_components:
  - source:
      type: git
      url: https://github.com/nkinnan/esphome-pace-bms
      ref: "initial_commit"
    components: [ pace_bms ]
    refresh: 1s

uart:
    id: uart_0
    baud_rate: 9600
    tx_pin: GPIO1
    rx_pin: GPIO3

pace_bms:
  id: pace_bms_at_address_1
  address: 1
  protocol_version: 0x25
  uart_id: uart_0
  flow_control_pin: GPIO0 
  update_interval: 5s
  request_throttle: 50ms 
  response_timeout: 1000ms 