substitutions:
  name: "esp32-c3-supermini-jk48v100"
  friendly_name: "ESP32-C3-Supermini JK48V100 Battery"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false
  project:
    name: esphome.web
    version: dev
  libraries:
    - WiFi
    - FS
    - Update
    # huge improvement to event throughput to the on-device web_server dashboard
    #- ESPAsyncWebServer-esphome=https://github.com/nkinnan/ESPAsyncWebServer#async_event_source_yield
    - ESPAsyncWebServer-esphome=symlink://C:\Users\nkinnan\Documents\git\ESPAsyncWebServer

esp32:
  board: esp32-c3-devkitm-1
  variant: esp32c3
  framework:
    type: arduino

# Enable logging
logger:
  #hardware_uart: UART1 # using UART0 for BMS communications
  #level: INFO
  #level: DEBUG
  level: VERBOSE
  #level: VERY_VERBOSE

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:
- platform: esphome

wifi:
  # Set up a wifi access point
  ap: {}

# To have a "next url" for improv serial
web_server:
  # uses an extra 76KB (V3) or 12KB (V2) worth of flash, but avoids referencing external web resources for 
  #     situations where you won't have internet while accessing the on-device dashboard
  #local: true
  version: 3

external_components:
  - source:
      #type: git
      #url: https://github.com/nkinnan/esphome-pace-bms
      #ref: "initial_commit"
      type: local
      path: C:\Users\nkinnan\Documents\git\esphome-pace-bms\components
    components: [ pace_bms ]
    refresh: 1s
    
  - source:
      type: git
      url: https://github.com/nkinnan/esphome
      ref: "make_time_dependency_optional"
      #type: local
      #path: C:\Users\nkinnan\Documents\git\esphome\esphome\components
    components: [ datetime ]
    refresh: 1s
    


    ##### board: https://europe1.discourse-cdn.com/arduino/optimized/4X/9/2/f/92f1e8e2fcc888726ff7838dad725dd94f43438d_2_690x301.jpeg


debug:
  update_interval: 1s


uart:
    id: uart_0
    baud_rate: 9600
    tx_pin: GPIO2
    rx_pin: GPIO1


pace_bms:
  id: pace_bms_at_address_1
  address: 1
  protocol_version: 0x25
  uart_id: uart_0
  flow_control_pin: GPIO0 # this will be brought high when writing to the bus - needed for RS485 communications, it should be omitted with RS232
  update_interval: 5s
  request_throttle: 50ms # this also helps to limit the rate at which things are sent to Home Assistant since updates can be dropped if sent too quickly
  response_timeout: 1000ms # responses are typically immediate, but I do occasionally see a larger delay after writing a value


sensor:
  - platform: debug
    free:
      name: "Heap Free"
      unit_of_measurement: kB
      accuracy_decimals: 3
      filters:
        - multiply: 0.001
#    block:
#      name: "Heap Max Block"
#      unit_of_measurement: kB
#      accuracy_decimals: 3
#      filters:
#        - multiply: 0.001
#    fragmentation:
#      name: "Heap Fragmentation"
    loop_time:
      name: "Loop Time"
# ESP-32 only
#    psram:
#      name: "Free PSRAM"

  - platform: uptime
    update_interval: 1s
    type: seconds
    name: "Uptime"



  - platform: pace_bms
    pace_bms_id: pace_bms_at_address_1

    cell_count:
      name: "Cell Count"


    temperature_count:
      name: "Temperature Count"

    temperature_01:
      name: "Cell Temperature 1"
    temperature_02:
      name: "Cell Temperature 2"
    temperature_03:
      name: "Cell Temperature 3"
    temperature_04:
      name: "Cell Temperature 4"
    temperature_05:
      name: "MOSFET Temperature"
    temperature_06:
      name: "Environment Temperature"

    total_voltage:
      name: "Total Voltage"
    current:
      name: "Current"
    power:
      name: "Power"

    remaining_capacity:
      name: "Remaining Capacity"
    full_capacity:
      name: "Full Capacity"
    design_capacity:
      name: "Design Capacity"

    cycle_count:
      name: "Cycle Count"
    state_of_charge:
      name: "State of Charge"
    state_of_health:
      name: "State of Health"

    min_cell_voltage:
      name: "Min Cell Voltage"
    max_cell_voltage:
      name: "Max Cell Voltage"
    avg_cell_voltage:
      name: "Avg Cell Voltage"
    max_cell_differential:
      name: "Max Cell Differential"




number:

  - platform: pace_bms
    pace_bms_id: pace_bms_at_address_1



datetime:
  - platform: pace_bms
    pace_bms_id: pace_bms_at_address_1

    system_date_and_time:
      name: "System Date and Time"